=== Nosperato/scala/test/files/xml/lnk.dtd
<!-- $Id$ -->

<!ELEMENT lnkDB          ((link|linkgroup)*)>

<!ELEMENT linkgroup      (groupname, (link|linkgroup)*)>
<!ELEMENT link           (name, description?)>

<!ATTLIST link
          target CDATA #REQUIRED>

<!ELEMENT groupname      (#PCDATA)>
<!ELEMENT name           (#PCDATA)>
<!ELEMENT description    (#PCDATA)>

=== Nosperato/scala/test/files/xml/lnk.xml
<!-- $Id$ -->

<!DOCTYPE lnkDB SYSTEM "lnk.dtd">
<!-- try this DOCTYPE lnkDB SYSTEM "lnkDB.dtd" [ <!ELEMENT newEl (link*)> ] -->
<lnkDB>
  <linkgroup>
    <groupname>LDAP Links</groupname>

    <link target="http://www.openldap.org/doc/">
      <name>OpenLDAP Administration Guide</name>
      <description>contains very readable section "What is LDAP"</description>
    </link>

    <linkgroup>
      <groupname>LDAP RFCs</groupname>

      <link target="ftp://ftp.isi.edu/in-notes/rfc2251.txt">
        <name>RFC2251 Lightweight Directory Access Protocol (v3)</name>
      </link>

      <link target="ftp://ftp.isi.edu/in-notes/rfc2252.txt">
        <name>Lightweight Directory Access Protocol (v3):
          Attribute Syntax Definitions</name>
      </link>

      <link target="ftp://ftp.isi.edu/in-notes/rfc2253.txt">
        <name>Lightweight Directory Access Protocol (v3):
          UTF-8 String Representation of Distinguished Names
        </name>
      </link>

      <link target="ftp://ftp.isi.edu/in-notes/rfc2254.txt">
        <name>The String Representation of LDAP Search Filters</name>
      </link>

    </linkgroup><!-- LDAP RFCs -->


    <linkgroup>

      <groupname>LDAP and Lotus Notes</groupname>

      <link target="http://www.shmoo.com/mail/fw1/jul99/msg00040.html">
        <name>LDAP enabled on Notes... to change settings</name>
      </link>

      <link target="http://www.openldap.org/lists/openldap-general/200103/msg00004.html">
        <name>Replicating Notes data to OpenLDAP</name>
      </link>

    </linkgroup><!-- LDAP and Lotus Notes -->

  </linkgroup><!-- LDAP links -->
</lnkDB>
